#!/bin/bash
# Phase 4D P1.5: reproducible signed-app build.
#
# Codex review on PR #20: the previous Phase 4 / Phase 4D
# instructions asked Jason to manually edit Xcode build phases
# (Run Script + Copy Files), which means a clean checkout cannot
# produce a working app and CI's green build doesn't prove the
# helper is embedded. This script fixes that — a clean checkout
# plus `./scripts/build_signed_app.sh` produces a signed .app with
# the helper binary + LaunchAgent plist in place at the right
# paths.
#
# What it does:
#   1. Build the Swift helper in release mode.
#   2. Build the macOS app via xcodebuild.
#   3. Copy `HelperSwift/.build/release/cli_pulse_helper` into
#      `<App>/Contents/Helpers/cli_pulse_helper`.
#   4. Copy `CLI Pulse Bar/CLI Pulse Bar/HelperAgent.plist` into
#      `<App>/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist`.
#   5. Codesign the embedded helper binary with the app's signing
#      identity (so SMAppService.register accepts it).
#   6. Re-sign the .app so the additions are part of the
#      signature seal.
#   7. Verify the final bundle structure.
#
# Usage:
#   ./scripts/build_signed_app.sh [Debug|Release] [<output-dir>]
#
# Defaults: configuration=Debug, output-dir=./build_app_output.
#
# CI integration: invoke this script instead of raw xcodebuild.
# A passing CI run proves the helper IS embedded + signed in the
# shipped artifact.
#
# Why this approach instead of pbxproj edits:
#   - pbxproj editing via Ruby `xcodeproj` adds a toolchain
#     dependency CI would have to install.
#   - pbxproj is regenerated by Xcode UI in subtle ways; manual
#     edits create review churn.
#   - The script works identically from CI, from Jason's
#     terminal, and as a post-build step a Run Script phase
#     can shell out to. Single source of truth.

set -euo pipefail

CONFIGURATION="${1:-Debug}"
OUTPUT_DIR="${2:-$PWD/build_app_output}"

# v1.19: opt-in flag for the Developer ID DMG pipeline.
# Notarization REQUIRES a timestamped signature (Apple's timestamp
# service), but the ad-hoc/dev path uses --timestamp=none for speed
# (CI runs hit this path; an Apple-side timestamp call adds 5-15s per
# nested binary and can fail transiently). Default keeps the historical
# behaviour; build_devid_dmg.sh sets CODESIGN_TIMESTAMP=1 before
# invoking this script.
if [[ -n "${CODESIGN_TIMESTAMP:-}" ]]; then
    CODESIGN_TIMESTAMP_FLAG="--timestamp"
else
    CODESIGN_TIMESTAMP_FLAG="--timestamp=none"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SWIFT_PKG_DIR="$PROJECT_ROOT/HelperSwift"
APP_PROJECT="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar.xcodeproj"
APP_SCHEME="CLI Pulse Bar"
PLIST_TEMPLATE="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar/HelperAgent.plist"
DERIVED_DATA="$OUTPUT_DIR/DerivedData"
# v1.34 DEVID keychain fix: the LaunchAgent helper is a BARE Mach-O and cannot
# embed a provisioning profile, so on the unsandboxed Developer-ID build it must
# carry NO restricted entitlements (keychain/app-groups/team-id) — otherwise AMFI
# SIGKILLs it at launch. The app + LoginItem are .app bundles and instead EMBED a
# Developer ID provisioning profile (below) that authorises keychain-access-groups.
# Non-DEVID (Debug-CI) keeps the historical entitlements (it never launches).
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    HELPER_ENTITLEMENTS="$SWIFT_PKG_DIR/cli_pulse_helper_devid.entitlements"
else
    HELPER_ENTITLEMENTS="$SWIFT_PKG_DIR/cli_pulse_helper.entitlements"
fi
# Developer ID provisioning profiles (committed; long-lived — exp 2044). Embedded
# at Contents/embedded.provisionprofile in the DEVID app + LoginItem so AMFI
# authorises their keychain-access-groups. Created via the App Store Connect API
# (MAC_APP_DIRECT; grants keychain-access-groups KHMK6Q3L3K.*).
DEVID_PROFILES_DIR="$PROJECT_ROOT/scripts/devid-profiles"
APP_PROVISION_PROFILE="$DEVID_PROFILES_DIR/CLI_Pulse_Bar_devid.provisionprofile"
LOGINITEM_PROVISION_PROFILE="$DEVID_PROFILES_DIR/CLIPulseHelper_devid.provisionprofile"
APP_ENTITLEMENTS_SAVED="$OUTPUT_DIR/app_entitlements.plist"

# W1-A (2026-06-28): team prefix used to expand $(AppIdentifierPrefix) in the
# keychain-access-group. `codesign --entitlements` does NOT expand Xcode build
# macros, so signing from a raw plist ships the LITERAL
# "$(AppIdentifierPrefix)group.yyh.CLI-Pulse" string → keychain sharing breaks.
# Matches the hard-coded team id in HelperSwift/cli_pulse_helper.entitlements
# and CLI Pulse Bar/scripts/build-appstore.sh (KHMK6Q3L3K).
APP_IDENTIFIER_PREFIX="KHMK6Q3L3K."

# Expand Xcode entitlement macros into a plist codesign can use verbatim, then
# assert no "$(" remains. plutil canonicalises (and drops XML comments) first.
# Usage: expand_entitlements SRC DST
expand_entitlements() {
    local src="$1" dst="$2"
    /usr/bin/plutil -convert xml1 -o "$dst" "$src" || {
        echo "error: plutil could not read entitlements source: $src" >&2
        exit 2
    }
    /usr/bin/sed -i '' \
        -e "s/\$(AppIdentifierPrefix)/${APP_IDENTIFIER_PREFIX}/g" \
        -e "s/\$(TeamIdentifierPrefix)/${APP_IDENTIFIER_PREFIX}/g" \
        "$dst"
    if /usr/bin/grep -q '\$(' "$dst"; then
        echo "error: unexpanded macro remains in $dst after expand_entitlements:" >&2
        /usr/bin/grep -n '\$(' "$dst" >&2
        exit 2
    fi
}

# 1. Build the Swift helper.
echo "==> [1/7] Building Swift helper (release) ..."
cd "$SWIFT_PKG_DIR"
swift build -c release
HELPER_BIN="$SWIFT_PKG_DIR/.build/release/cli_pulse_helper"
[[ -x "$HELPER_BIN" ]] || { echo "error: helper binary missing at $HELPER_BIN" >&2; exit 1; }
HELPER_SIZE="$(du -h "$HELPER_BIN" | cut -f1)"
echo "    built: $HELPER_BIN ($HELPER_SIZE)"

# 2. Build the macOS app.
echo "==> [2/7] Building CLI Pulse Bar.app ($CONFIGURATION) ..."
cd "$PROJECT_ROOT/CLI Pulse Bar"
# Strip lingering .DS_Store xattrs that codesign rejects on
# nested helper targets ("resource fork, Finder information, or
# similar detritus not allowed"). xattr returns 0 even when nothing
# matches, so the `|| true` is defensive.
find . -name ".DS_Store" -exec rm -f {} + 2>/dev/null || true

# v1.19: opt-in compilation flags for the Developer ID DMG pipeline.
# DEVID_BUILD_FLAG=1 sets SWIFT_ACTIVE_COMPILATION_CONDITIONS to include
# DEVID_BUILD so Swift code can `#if DEVID_BUILD` to gate the AppUpdater,
# subscription bypass, MAS-auto-update banner, etc. Default empty =
# Release/Debug builds behave exactly as before (MAS-equivalent
# compilation). build_devid_dmg.sh sets DEVID_BUILD_FLAG=1.
EXTRA_XCODEBUILD_SETTINGS=()
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    EXTRA_XCODEBUILD_SETTINGS+=("SWIFT_ACTIVE_COMPILATION_CONDITIONS=\$(inherited) DEVID_BUILD")
    # DEVID ships arm64-only BY POLICY (post-1.42.0 audit): every published
    # DMG has been arm64-labelled since v1.19, the manifest `arch` is pinned
    # to "arm64" by shipped apps' AppUpdater.assertArchitectureMatches, and
    # the embedded helpers (cli_pulse_helper, machine-root-helper) are
    # arm64-only — a universal main binary just produced an app that LAUNCHED
    # on Intel with its helper features silently dead, plus a binary/label
    # mismatch. ARCHS here makes the artifact match the label; on Intel,
    # macOS now says "requires Apple Silicon" up front instead. Scoped to
    # DEVID on purpose — the MAS build stays universal for Intel App Store
    # users (build-appstore.sh is untouched by this script).
    EXTRA_XCODEBUILD_SETTINGS+=("ARCHS=arm64" "ONLY_ACTIVE_ARCH=NO")
fi

xcodebuild \
    -project "$APP_PROJECT" \
    -scheme "$APP_SCHEME" \
    -configuration "$CONFIGURATION" \
    -derivedDataPath "$DERIVED_DATA" \
    build \
    CODE_SIGNING_ALLOWED=NO \
    CODE_SIGN_IDENTITY="" \
    CODE_SIGN_STYLE=Manual \
    DEVELOPMENT_TEAM="" \
    ${EXTRA_XCODEBUILD_SETTINGS[@]+"${EXTRA_XCODEBUILD_SETTINGS[@]}"}

APP_PATH="$DERIVED_DATA/Build/Products/$CONFIGURATION/CLI Pulse Bar.app"
[[ -d "$APP_PATH" ]] || { echo "error: built .app not found at $APP_PATH" >&2; exit 1; }
echo "    built: $APP_PATH"

# DEVID arch gate: the artifact must MATCH the "arm64" release label. The
# 1.42.0 audit found the binary was silently universal while the DMG name,
# manifest arch, and helpers all said arm64 — a mismatch nobody could see
# because nothing checked lipo output against the label. Fail loudly here.
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    MAIN_ARCHS="$(lipo -archs "$APP_PATH/Contents/MacOS/CLI Pulse Bar" 2>/dev/null || true)"
    if [[ "$MAIN_ARCHS" != "arm64" ]]; then
        echo "error: DEVID build must be arm64-only to match the release label," >&2
        echo "       but lipo reports: '${MAIN_ARCHS:-<unreadable>}'" >&2
        exit 7
    fi
    echo "    arch gate: main binary is arm64-only (matches release label) ✓"
fi

# 3. Copy helper binary into Contents/Helpers/.
echo "==> [3/7] Embedding helper at Contents/Helpers/ ..."
mkdir -p "$APP_PATH/Contents/Helpers"
cp "$HELPER_BIN" "$APP_PATH/Contents/Helpers/cli_pulse_helper"
chmod +x "$APP_PATH/Contents/Helpers/cli_pulse_helper"

# 3b. Embed the bundled tmux (M4.4b). External-session control needs tmux and
#     clean Macs have none. The binary is a universal, Developer-ID-signed,
#     hardened-runtime artifact produced by
#     `CLI Pulse Bar/scripts/build-tmux-universal.sh`, and is git-ignored — so a
#     checkout that has never run that script silently has no tmux.
#
#     Since 1.42.0 tmux-wrap is a SHIPPED feature, so a distributable build
#     (DEVID_BUILD_FLAG=1) without tmux is a defect, not a variation: the app
#     looks fine, the UI renders, and wrapping just never works on any Mac
#     without Homebrew tmux. That failure is invisible in CI and in every
#     automated check — it only shows up as a dead button on a user's machine,
#     which is exactly why this must be a hard error rather than a notice.
#     Local dev builds stay unblocked.
#
#     Sits next to the helper so the helper resolves it via
#     `shell_integration.resolve_tmux_bin()`.
TMUX_BUNDLED="$PROJECT_ROOT/CLI Pulse Bar/Resources/bin/tmux"
if [[ -f "$TMUX_BUNDLED" ]]; then
    echo "==> [3b] Embedding bundled tmux at Contents/Helpers/tmux ..."
    cp "$TMUX_BUNDLED" "$APP_PATH/Contents/Helpers/tmux"
    chmod +x "$APP_PATH/Contents/Helpers/tmux"
elif [[ "${DEVID_BUILD_FLAG:-0}" == "1" ]]; then
    echo "error: no bundled tmux at $TMUX_BUNDLED" >&2
    echo "       A distributable build MUST embed tmux — tmux-wrap (shipped in 1.42.0)" >&2
    echo "       silently does nothing on Macs without Homebrew tmux." >&2
    echo "       Build it first: 'CLI Pulse Bar/scripts/build-tmux-universal.sh'" >&2
    exit 6
else
    echo "    (no bundled tmux at $TMUX_BUNDLED — run 'CLI Pulse Bar/scripts/build-tmux-universal.sh' to include it)"
    echo "    NOTE: tmux-wrap will not work in this build. Distributable builds hard-fail here."
fi

# 4. Copy LaunchAgent plist into Contents/Library/LaunchAgents/.
echo "==> [4/7] Embedding LaunchAgent plist at Contents/Library/LaunchAgents/ ..."
mkdir -p "$APP_PATH/Contents/Library/LaunchAgents"
cp "$PLIST_TEMPLATE" "$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist"

# 4b. (DEVID only) Embed the fan-control ROOT daemon (M3) + its SMAppService
#     LaunchDaemon plist. Root SMC write needs a privileged daemon, registered by
#     the app via SMAppService.daemon (FanDaemonInstaller). NOT in the MAS build
#     (sandbox forbids it) — this whole block is DEVID-gated. Signed below, before
#     the final app re-seal.
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    echo "==> [4b] Building + embedding fan-control root daemon (DEVID) ..."
    ( cd "$PROJECT_ROOT/MachineRootHelper" && swift build -c release )
    FAN_DAEMON_BIN="$PROJECT_ROOT/MachineRootHelper/.build/release/machine-root-helper"
    [[ -x "$FAN_DAEMON_BIN" ]] || { echo "error: fan daemon missing at $FAN_DAEMON_BIN" >&2; exit 1; }
    cp "$FAN_DAEMON_BIN" "$APP_PATH/Contents/MacOS/machine-root-helper"
    chmod +x "$APP_PATH/Contents/MacOS/machine-root-helper"
    mkdir -p "$APP_PATH/Contents/Library/LaunchDaemons"
    cp "$PROJECT_ROOT/MachineRootHelper/install/yyh.CLI-Pulse.machine-root-helper.plist" \
       "$APP_PATH/Contents/Library/LaunchDaemons/yyh.CLI-Pulse.machine-root-helper.plist"
    echo "    embedded machine-root-helper + LaunchDaemon plist"
fi

# 5. Resolve signing identity + capture original app entitlements
#    BEFORE we touch the bundle. Codex P1.C review: the previous
#    `--force --deep` re-sign stripped sandbox / app-group
#    entitlements that Xcode's signing applied. The fix is to:
#      (a) extract the existing app entitlements plist,
#      (b) sign the helper with its OWN entitlements (no sandbox,
#          minimal Hardened Runtime),
#      (c) re-sign the app explicitly preserving its entitlements
#          via `--preserve-metadata=entitlements,requirements,flags`.
echo "==> [5/7] Resolving signing identity + entitlements source ..."
SIGN_IDENTITY="-"   # ad-hoc by default
if [[ -n "${CODE_SIGN_IDENTITY:-}" ]]; then
    SIGN_IDENTITY="$CODE_SIGN_IDENTITY"
fi
# Use the source entitlements file Xcode reads from
# CODE_SIGN_ENTITLEMENTS. With CODE_SIGNING_ALLOWED=NO Xcode
# doesn't emit a per-build .xcent, so we sign with the source
# file directly. This is the EXACT same input Xcode would have
# used had signing been on, so sandbox + app-group entitlements
# survive intact.
# W1-A: the Developer-ID build signs with an UNSANDBOXED entitlements file so
# the in-app terminal (gated on !isSandboxed) becomes visible. The MAS archive
# (build-appstore.sh via xcodebuild) is untouched and keeps the sandboxed
# CLI_Pulse_Bar.entitlements. Both paths get macro expansion.
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    APP_ENTITLEMENTS_SOURCE="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar/CLI_Pulse_Bar_devid.entitlements"
else
    APP_ENTITLEMENTS_SOURCE="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar/CLI_Pulse_Bar.entitlements"
fi
if [[ ! -f "$APP_ENTITLEMENTS_SOURCE" ]]; then
    echo "error: app entitlements source missing at $APP_ENTITLEMENTS_SOURCE" >&2
    exit 2
fi
expand_entitlements "$APP_ENTITLEMENTS_SOURCE" "$APP_ENTITLEMENTS_SAVED"
echo "    using: $APP_ENTITLEMENTS_SOURCE -> $APP_ENTITLEMENTS_SAVED (macros expanded)"

# 6. Sign the embedded helper with its own minimal entitlements,
#    then re-sign the app preserving its sandbox / app-group
#    entitlements. Re-sign nested frameworks first because they
#    have their own _CodeSignature/CodeResources that get
#    invalidated by xattr -c on the parent.
echo "==> [6/7] Codesigning helper + re-signing .app (identity=$SIGN_IDENTITY) ..."
# Strip xattrs recursively. Source files under macOS dev
# workflows pick up `com.apple.provenance` / `com.apple.FinderInfo`
# xattrs from Finder / curl, and Xcode propagates them into the
# bundle on copy. We hit EVERYTHING — frameworks too — because
# the bottom-up re-sign below regenerates each framework's
# _CodeSignature/CodeResources.
xattr -cr "$APP_PATH" 2>/dev/null || true

# Bottom-up re-sign of every nested signed bundle inside the
# app. Order matters: deepest frameworks first, then login-item
# .apps, then the parent app on top. We do NOT use `codesign
# --deep` because that would apply the parent's entitlements to
# every nested binary (helper would inherit sandbox, frameworks
# would get group-container). The bottom-up walk lets each
# bundle keep its own entitlements.
echo "    re-signing nested bundles bottom-up ..."
python3 - <<PYEOF "$APP_PATH" "$SIGN_IDENTITY" "$CODESIGN_TIMESTAMP_FLAG"
import os, sys, subprocess
app_path, sign_identity = sys.argv[1], sys.argv[2]
matches = []
for root, dirs, _files in os.walk(app_path):
    for d in list(dirs):
        if d.endswith((".framework", ".app", ".xpc", ".dylib")):
            matches.append(os.path.join(root, d))
# Sort by path length descending → deepest first.
matches.sort(key=lambda p: -len(p))
for p in matches:
    # v1.19 macOS 26.5 SDK: signing an inner framework regenerates
    # _CodeSignature/CodeResources on the parent bundle and the
    # parent picks up com.apple.provenance + com.apple.FinderInfo
    # xattrs from the macOS file-creation path. The top-of-script
    # xattr -cr does not help because those xattrs come BACK after
    # each nested sign. Strip immediately before each codesign call
    # so the bundle being signed never has detritus.
    subprocess.call(["xattr", "-cr", p], stderr=subprocess.DEVNULL)
    rc = subprocess.call([
        "codesign", "--force", "--options", "runtime", sys.argv[3],
        "--sign", sign_identity, p,
    ])
    if rc != 0:
        # Surface the failure clearly so the outer shell sees a
        # non-zero exit. The original subprocess.call swallowed
        # codesign errors silently, letting builds proceed past
        # broken signatures into notarize failures.
        sys.stderr.write(f"codesign failed for {p} (rc={rc})\n")
        sys.exit(rc)
PYEOF
# Helper: NOT sandboxed (it's a LaunchAgent), but Hardened Runtime
# is on (--options runtime) for notarisation. Expand $(AppIdentifierPrefix)
# in its keychain group first (W1-A: codesign won't, so it previously shipped
# the literal macro → keychain sharing broken).
HELPER_ENTITLEMENTS_EXPANDED="$OUTPUT_DIR/helper_entitlements.plist"
expand_entitlements "$HELPER_ENTITLEMENTS" "$HELPER_ENTITLEMENTS_EXPANDED"
xattr -cr "$APP_PATH/Contents/Helpers/cli_pulse_helper" 2>/dev/null || true
codesign --force --options runtime "$CODESIGN_TIMESTAMP_FLAG" \
    --entitlements "$HELPER_ENTITLEMENTS_EXPANDED" \
    --sign "$SIGN_IDENTITY" \
    "$APP_PATH/Contents/Helpers/cli_pulse_helper"

# (DEVID only) Sign the fan-control root daemon — bare Mach-O in Contents/MacOS/,
# Hardened Runtime, NO entitlements (root SMC write needs none; the XPC gate
# authenticates the app by Team-ID + identifier, not by daemon entitlements).
# Signed here, before the final app re-seal below, so it's part of the seal.
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    xattr -cr "$APP_PATH/Contents/MacOS/machine-root-helper" 2>/dev/null || true
    codesign --force --options runtime "$CODESIGN_TIMESTAMP_FLAG" \
        --sign "$SIGN_IDENTITY" \
        "$APP_PATH/Contents/MacOS/machine-root-helper"
    echo "    signed fan daemon (Hardened Runtime, no entitlements)"
fi

# W1-A: re-sign the embedded LoginItem (CLIPulseHelper.app) with its OWN
# entitlements. The bottom-up walk above re-signed nested .app bundles with NO
# entitlements, which STRIPPED this LoginItem's sandbox + app-group + keychain
# (prior DEVID builds ran it entitlement-less → recurring keychain prompts /
# legacy fallback). DEVID → UNSANDBOXED entitlements: the app is unsandboxed and
# CODE_SIGNING_ALLOWED=NO embeds no provisioning profile, so a sandboxed nested
# item requesting keychain/app-group has nothing to authorise the restricted
# entitlements and taskgated can reject it on SMAppService.loginItem launch
# (HelperLogin.register). Non-DEVID (MAS-shaped) → the sandboxed entitlements.
LOGIN_ITEM_APP="$APP_PATH/Contents/Library/LoginItems/CLIPulseHelper.app"
# The LoginItem (CLIPulseHelper.app) is embedded by Xcode as a Copy Files build
# phase / target dependency, so it is ALWAYS present in a real build. The
# semantic verifier in step 7 already asserts it present UNCONDITIONALLY
# (`check(os.path.isdir(login_app), "LoginItem not found …")`). Make the signing
# step equally strict so a missing LoginItem fails HERE — clear and early —
# instead of: (a) slipping through this `else` branch unsigned (entitlements
# stripped by the bottom-up nested-bundle re-sign above) only to fail the
# verifier with a more confusing error, or (b) on any future non-verified code
# path, shipping an entitlement-stripped LoginItem that taskgated rejects at
# SMAppService.loginItem launch.
[[ -d "$LOGIN_ITEM_APP" ]] || {
    echo "error: LoginItem missing at $LOGIN_ITEM_APP — expected Xcode to embed CLIPulseHelper.app (Copy Files phase / target dependency)" >&2
    exit 2
}
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    LOGIN_ITEM_ENT_SOURCE="$PROJECT_ROOT/CLI Pulse Bar/CLIPulseHelper/CLIPulseHelper_devid.entitlements"
else
    LOGIN_ITEM_ENT_SOURCE="$PROJECT_ROOT/CLI Pulse Bar/CLIPulseHelper/CLIPulseHelper.entitlements"
fi
[[ -f "$LOGIN_ITEM_ENT_SOURCE" ]] || {
    echo "error: LoginItem entitlements missing at $LOGIN_ITEM_ENT_SOURCE" >&2; exit 2; }
LOGIN_ITEM_ENT_EXPANDED="$OUTPUT_DIR/loginitem_entitlements.plist"
expand_entitlements "$LOGIN_ITEM_ENT_SOURCE" "$LOGIN_ITEM_ENT_EXPANDED"
# v1.34: embed the Developer ID profile so AMFI authorises the LoginItem's
# keychain-access-groups on the unsandboxed DEVID build (it hydrates secrets from
# the Keychain). DEVID only; the profile is sealed by the codesign below.
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    [[ -f "$LOGINITEM_PROVISION_PROFILE" ]] || {
        echo "error: LoginItem Developer ID profile missing at $LOGINITEM_PROVISION_PROFILE" >&2; exit 2; }
    cp "$LOGINITEM_PROVISION_PROFILE" "$LOGIN_ITEM_APP/Contents/embedded.provisionprofile"
    echo "    embedded LoginItem Developer ID profile"
fi
xattr -cr "$LOGIN_ITEM_APP" 2>/dev/null || true
codesign --force --options runtime "$CODESIGN_TIMESTAMP_FLAG" \
    --entitlements "$LOGIN_ITEM_ENT_EXPANDED" \
    --sign "$SIGN_IDENTITY" \
    "$LOGIN_ITEM_APP"
echo "    signed LoginItem with $(basename "$LOGIN_ITEM_ENT_SOURCE") (macros expanded)"

# v1.34: embed the Developer ID profile into the app bundle so AMFI authorises
# its keychain-access-groups (account auth tokens + provider API keys) on the
# unsandboxed DEVID build. DEVID only; sealed by the app re-sign below. Without
# this the notarized app is AMFI-SIGKILLed at launch (verified).
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    [[ -f "$APP_PROVISION_PROFILE" ]] || {
        echo "error: app Developer ID profile missing at $APP_PROVISION_PROFILE" >&2; exit 2; }
    cp "$APP_PROVISION_PROFILE" "$APP_PATH/Contents/embedded.provisionprofile"
    echo "    embedded app Developer ID profile"
fi
# Re-sign the app with the original Xcode-emitted entitlements
# (.xcent file we located above). NOT --deep — that would re-sign
# every nested binary with our top-level entitlements (overwriting
# the helper's just-applied minimal set).
# v1.49: the single `xattr -cr` here is NOT enough, and this is a real
# failure rather than a theoretical one — it blocked the 1.49.0 DEVID build
# twice in a row, deterministically, on a clean staging tree:
#
#   CLI Pulse Bar.app: resource fork, Finder information, or similar
#   detritus not allowed
#
# Cause: the SAME mechanism the nested-sign loop above already documents,
# now at the top level. Signing a nested bundle regenerates
# `_CodeSignature/CodeResources` on its parent, and the parent picks up
# `com.apple.provenance` + `com.apple.FinderInfo` from the macOS
# file-creation path. Six bundle directories carried FinderInfo when this
# failed: the app, both CLIPulseCore resource bundles, both
# Sentry.frameworks and the LoginItem app. A single strip loses the race
# because the signing machinery re-creates them; only provenance is
# tolerated by codesign, which is why just the outer sign died.
#
# ⚠️ CORRECTION, 2026-08-18. An earlier version of this comment blamed
# iCloud — "~/Documents is a Desktop & Documents container, the file
# provider re-stamps the xattrs". That is WRONG and was asserted without
# checking, against a `check_no_duplicate_sources.sh` comment that had
# already investigated and rejected the same theory. Verified since:
# Desktop & Documents sync is OFF (no Desktop/Documents under
# com~apple~CloudDocs), ~/Documents is a plain directory and not a
# symlink, and SOURCE files carry no `com.apple.fileprovider` at all —
# only build output did. `brctl status` reporting one idle CloudDocs
# container says nothing about this repo. Do not "fix" this by moving the
# build out of ~/Documents; it would change nothing.
#
# So: strip and sign as one retried unit. A signature that took two
# attempts is byte-identical to one that took one, so retrying costs
# nothing but the wall-clock. Failing after the last attempt is loud and
# non-zero — `set -e` is not relied on here because the retry needs to
# inspect the exit code.
sign_app_stripping_detritus() {
    local attempt
    for attempt in 1 2 3 4 5; do
        # `-c` clears every xattr including FinderInfo; the app bundle is
        # large, so this is the slow part, not codesign.
        xattr -cr "$APP_PATH" 2>/dev/null || true
        if codesign --force --options runtime "$CODESIGN_TIMESTAMP_FLAG" \
            --entitlements "$APP_ENTITLEMENTS_SAVED" \
            --sign "$SIGN_IDENTITY" \
            "$APP_PATH"
        then
            [[ $attempt -gt 1 ]] && \
                echo "    (top-level signature succeeded on attempt $attempt — iCloud re-stamped xattrs mid-sign)"
            return 0
        fi
        echo "    top-level codesign attempt $attempt failed; re-stripping xattrs and retrying" >&2
        sleep 2
    done
    echo "error: top-level codesign failed after 5 attempts. If the message is" >&2
    echo "       'resource fork, Finder information, or similar detritus not allowed'," >&2
    echo "       something is re-creating com.apple.FinderInfo on the bundle faster" >&2
    echo "       than we strip it. Check which xattr is actually present --" >&2
    echo "         xattr -r <app> | grep -E 'FinderInfo|ResourceFork'" >&2
    echo "       -- because com.apple.provenance is TOLERATED by codesign and is" >&2
    echo "       not the culprit, and raise the attempt count if it is a race." >&2
    return 1
}
sign_app_stripping_detritus

# 7. Verify.
echo "==> [7/7] Verifying bundle ..."
test -x "$APP_PATH/Contents/Helpers/cli_pulse_helper"
test -f "$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist"
# (DEVID only) fan daemon + its SMAppService plist must be embedded.
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    test -x "$APP_PATH/Contents/MacOS/machine-root-helper"
    test -f "$APP_PATH/Contents/Library/LaunchDaemons/yyh.CLI-Pulse.machine-root-helper.plist"
    echo "    fan daemon + LaunchDaemon plist present"
fi
# v1.20: macOS 26.5 (post-26.5.1) re-adds com.apple.provenance xattrs to
# _CodeSignature/CodeResources files at LaunchServices registration time
# (faster than we can strip them — even an immediate `xattr -cr` followed
# by `codesign --verify --deep --strict` loses the race). The xattrs are
# NOT part of the signed content (codesign emits them on its own files),
# and notarytool + spctl don't flag their presence — only `--strict`
# verification does. Drop `--strict` here. Notarize + stapler validate +
# spctl assess in later steps remain the real gates. If a corruption ever
# bypasses the structural codesign verify (which IS still in --deep mode),
# notarytool will reject the submission and we'd see it there.
xattr -cr "$APP_PATH" 2>/dev/null || true
codesign --verify --deep "$APP_PATH"

# W1-A: semantic entitlement verification of the SIGNED products (not the
# source files). Replaces the old substring greps with plist parsing so we can
# assert the full matrix:
#   * DEVID app has NO app-sandbox; non-DEVID app HAS it.
#   * app + LoginItem carry application-group group.yyh.CLI-Pulse and keychain
#     group KHMK6Q3L3K.group.yyh.CLI-Pulse (exact, macro-expanded); on DEVID they
#     also EMBED a Developer ID provisioning profile that authorises those
#     restricted entitlements (else AMFI SIGKILLs them at launch — v1.34 fix).
#   * LaunchAgent helper is never sandboxed; on DEVID it carries NO restricted
#     entitlements at all (bare Mach-O can't embed a profile) — reaches the Group
#     Container by path. Non-DEVID keeps the historical keychain/app-group.
#   * no entitlement contains an unexpanded "$(" macro.
#   * (DEVID only) every signed binary has the Hardened Runtime flag — ad-hoc
#     signing ignores --options runtime, so this is gated off for the Debug CI.
IS_DEVID=0
[[ -n "${DEVID_BUILD_FLAG:-}" ]] && IS_DEVID=1
EXPECTED_KC_GROUP="${APP_IDENTIFIER_PREFIX}group.yyh.CLI-Pulse"
EXPECTED_APP_GROUP="group.yyh.CLI-Pulse"
python3 - "$APP_PATH" "$IS_DEVID" "$EXPECTED_KC_GROUP" "$EXPECTED_APP_GROUP" <<'PYEOF'
import os, sys, subprocess, plistlib

app_path, is_devid, kc_group, app_group = sys.argv[1], sys.argv[2] == "1", sys.argv[3], sys.argv[4]
helper_bin = os.path.join(app_path, "Contents/Helpers/cli_pulse_helper")
login_app  = os.path.join(app_path, "Contents/Library/LoginItems/CLIPulseHelper.app")
login_bin  = os.path.join(login_app, "Contents/MacOS/CLIPulseHelper")
errors = []

def read_entitlements(path):
    out = subprocess.run(["codesign", "-d", "--entitlements", ":-", path],
                         capture_output=True)
    data = out.stdout
    for marker in (b"<?xml", b"<plist", b"bplist00"):
        i = data.find(marker)
        if i >= 0:
            try:
                return plistlib.loads(data[i:])
            except Exception:
                pass
    try:
        return plistlib.loads(data)
    except Exception:
        return None

def cd_flags(path):
    out = subprocess.run(["codesign", "-d", "-v", path], capture_output=True)
    text = (out.stdout + out.stderr).decode("utf-8", "replace")
    for line in text.splitlines():
        if "flags=" in line:
            return line.strip()
    return ""

def check(cond, msg):
    if not cond:
        errors.append(msg)

def has_group(ent, key, val):
    return ent is not None and val in (ent.get(key) or [])

app_ent = read_entitlements(app_path)
helper_ent = read_entitlements(helper_bin)
login_ent = read_entitlements(login_bin) if os.path.isdir(login_app) else None

check(app_ent is not None, "could not read app entitlements")
if app_ent is not None:
    sb = bool(app_ent.get("com.apple.security.app-sandbox", False))
    if is_devid:
        check(not sb, "DEVID app MUST NOT be sandboxed (app-sandbox present)")
    else:
        check(sb, "non-DEVID app MUST be sandboxed (app-sandbox missing/false)")
    check(has_group(app_ent, "com.apple.security.application-groups", app_group),
          "app missing application-group %s" % app_group)
    check(has_group(app_ent, "keychain-access-groups", kc_group),
          "app keychain group != %s (got %r)" % (kc_group, app_ent.get("keychain-access-groups")))
    if is_devid:
        # v1.34: the embedded Developer ID profile is what AMFI uses to authorise
        # the app's keychain-access-groups (it grants KHMK6Q3L3K.*). Without it the
        # notarized app is SIGKILLed at launch.
        check(os.path.isfile(os.path.join(app_path, "Contents/embedded.provisionprofile")),
              "DEVID app missing Contents/embedded.provisionprofile (authorises keychain-access-groups)")

check(helper_ent is not None, "could not read LaunchAgent helper entitlements")
if helper_ent is not None:
    check(not bool(helper_ent.get("com.apple.security.app-sandbox", False)),
          "LaunchAgent helper MUST NOT be sandboxed")
    if is_devid:
        # v1.34: the bare-Mach-O LaunchAgent helper can't embed a provisioning
        # profile, so on the unsandboxed DEVID build it must carry NO restricted
        # entitlements — AMFI SIGKILLs an unsandboxed Developer-ID binary that has
        # keychain-access-groups/application-groups without a profile (verified).
        # It reaches the Group Container by absolute path + uses the file token.
        check(not helper_ent.get("keychain-access-groups"),
              "DEVID helper MUST NOT have keychain-access-groups (got %r)" % helper_ent.get("keychain-access-groups"))
        check(not helper_ent.get("com.apple.security.application-groups"),
              "DEVID helper MUST NOT have application-groups (got %r)" % helper_ent.get("com.apple.security.application-groups"))
    else:
        check(has_group(helper_ent, "com.apple.security.application-groups", app_group),
              "helper missing application-group %s" % app_group)
        check(has_group(helper_ent, "keychain-access-groups", kc_group),
              "helper keychain group != %s (got %r)" % (kc_group, helper_ent.get("keychain-access-groups")))

check(os.path.isdir(login_app), "LoginItem not found at %s" % login_app)
if login_ent is not None:
    sb = bool(login_ent.get("com.apple.security.app-sandbox", False))
    if is_devid:
        check(not sb, "DEVID LoginItem MUST NOT be sandboxed (no embedded profile to authorise restricted entitlements)")
    else:
        check(sb, "non-DEVID LoginItem MUST be sandboxed (MAS shape)")
    check(has_group(login_ent, "com.apple.security.application-groups", app_group),
          "LoginItem missing application-group %s" % app_group)
    check(has_group(login_ent, "keychain-access-groups", kc_group),
          "LoginItem keychain group != %s (got %r)" % (kc_group, login_ent.get("keychain-access-groups")))
    if is_devid:
        check(os.path.isfile(os.path.join(login_app, "Contents/embedded.provisionprofile")),
              "DEVID LoginItem missing Contents/embedded.provisionprofile (authorises keychain-access-groups)")
elif os.path.isdir(login_app):
    errors.append("could not read LoginItem entitlements")

for label, ent in (("app", app_ent), ("helper", helper_ent), ("LoginItem", login_ent)):
    if ent is not None and b"$(" in plistlib.dumps(ent):
        errors.append("%s entitlements contain unexpanded macro '$('" % label)

if is_devid:
    for label, p in (("app", app_path), ("helper", helper_bin), ("LoginItem", login_bin)):
        if os.path.exists(p):
            flags = cd_flags(p)
            check("runtime" in flags, "%s missing Hardened Runtime flag (got: %s)" % (label, flags))

if errors:
    sys.stderr.write("error: entitlement verification FAILED (DEVID=%s):\n" % is_devid)
    for e in errors:
        sys.stderr.write("  - %s\n" % e)
    sys.exit(2)
print("    entitlement verification OK (semantic; DEVID=%s)" % is_devid)
PYEOF
# Phase 4E e2e fix (2026-05-07): tilde paths in plist break
# launchd. Reject so the bug can't ship.
PLIST_PATH="$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist"
if [[ -f "$PLIST_PATH" ]]; then
    if /usr/libexec/PlistBuddy -c "Print :StandardOutPath" "$PLIST_PATH" 2>/dev/null | grep -q "~"; then
        echo "error: plist StandardOutPath contains '~' — launchd will not expand it" >&2
        exit 2
    fi
    if /usr/libexec/PlistBuddy -c "Print :StandardErrorPath" "$PLIST_PATH" 2>/dev/null | grep -q "~"; then
        echo "error: plist StandardErrorPath contains '~' — launchd will not expand it" >&2
        exit 2
    fi
fi
if [[ "$IS_DEVID" == "1" ]]; then
    echo "    OK: $APP_PATH signed UNSANDBOXED (DEVID); app/helper/LoginItem entitlements verified semantically (macros expanded, hardened runtime), plist clean"
else
    echo "    OK: $APP_PATH signed SANDBOXED (MAS-shaped); app/helper/LoginItem entitlements verified semantically (macros expanded), plist clean"
fi

echo ""
echo "Final layout:"
echo "  $APP_PATH/Contents/Helpers/cli_pulse_helper                       # Mach-O helper, signed"
echo "  $APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist # LaunchAgent plist"
echo ""
echo "Open the .app with Finder to test, or run:"
echo "  open '$APP_PATH'"
